name: Azure ML Environment and Component Setup

# Triggers the workflow on push or pull request events to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  azure-ml-setup:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Environment Setup
      - name: Azure -- Environment Setup
        uses: Azure/CLI@v2.0.0
        with:
          azcliversion: 2.53.0
          inlineScript: |
            az extension add --name ml
            az configure --defaults group=$GROUP workspace=$WORKSPACE location=$LOCATION
            az ml environment create --file ./environment/pillow.yaml
            az ml environment create --file ./environment/tensorflow.yaml

      # Component Setup
      - name: Azure -- Component Setup
        uses: Azure/CLI@v2.0.0
        with:
          azcliversion: 2.53.0
          inlineScript: |
            az extension add --name ml
            az configure --defaults group=$GROUP workspace=$WORKSPACE location=$LOCATION
            az ml components create --file ./components/dataprep/dataprep.yaml
            az ml components create --file ./components/dataprep/data_split.yaml
            az ml components create --file ./components/training/training.yaml
